# Numpy: Package for Multidimensional array
## Vector(1d)
### Matrix(2d or 1d)

In [2]:
import numpy as np

In [3]:
simple_list=[61,72,91]
np.array(simple_list)

array([61, 72, 91])

In [4]:
arr=np.array([11,12,13])
arr

array([11, 12, 13])

list_of_lists=[[1,2,3],[4,5,6],[7,8,9]]
np.array(list_of_lists)

In [6]:
np.arange(15,30)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [7]:
np.arange(15,30,5)

array([15, 20, 25])

In [8]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.ones((2,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [11]:
np.linspace(0,20,18)

array([ 0.        ,  1.17647059,  2.35294118,  3.52941176,  4.70588235,
        5.88235294,  7.05882353,  8.23529412,  9.41176471, 10.58823529,
       11.76470588, 12.94117647, 14.11764706, 15.29411765, 16.47058824,
       17.64705882, 18.82352941, 20.        ])

In [12]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
np.random.rand(2,5)

array([[0.90599795, 0.99132474, 0.1392954 , 0.57880664, 0.62671736],
       [0.35705529, 0.88752667, 0.52966414, 0.59696331, 0.94617514]])

In [14]:
np.random.rand(3,7)

array([[0.21427254, 0.82246698, 0.95937052, 0.84325946, 0.63877144,
        0.84905994, 0.49088056],
       [0.10944692, 0.0994675 , 0.54878373, 0.01565265, 0.20814299,
        0.20729525, 0.97462667],
       [0.96736793, 0.10730912, 0.83633189, 0.37286966, 0.38387031,
        0.47512416, 0.92077761]])

In [16]:
np.random.randint(4,10,2)

array([4, 8])

In [17]:
np.random.randint(20,60,70)

array([38, 31, 53, 29, 46, 51, 36, 23, 25, 26, 54, 34, 25, 53, 34, 45, 42,
       47, 38, 31, 33, 31, 33, 26, 57, 59, 41, 29, 41, 28, 20, 35, 23, 27,
       35, 30, 33, 40, 58, 36, 52, 24, 26, 44, 22, 54, 54, 31, 50, 32, 26,
       21, 42, 32, 29, 25, 42, 27, 34, 50, 50, 32, 29, 55, 24, 39, 46, 24,
       47, 54])

In [21]:
sample_array=np.arange(1,30,2)
sample_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [22]:
rand_array=np.random.randint(0,100,21)
rand_array

array([91, 95, 47, 55, 40,  3, 63,  9, 49, 14, 89, 59, 67,  8, 15,  0, 94,
       20, 99, 66, 54])

In [27]:
sample_array.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [28]:
rand_array.min()

0

In [29]:
rand_array.argmin()

15

In [30]:
sample_array

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29])

In [31]:
sample_array.shape

(15,)

In [33]:
sample_array.reshape(5,3)

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [34]:
sample_array.dtype

dtype('int32')

In [35]:
a=np.eye(4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [43]:
a.T

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [36]:
a=np.random.rand(2,4)
a

array([[0.31239006, 0.40068967, 0.38376579, 0.63737754],
       [0.73789298, 0.87150454, 0.52396758, 0.17962402]])

In [37]:
a.T

array([[0.31239006, 0.73789298],
       [0.40068967, 0.87150454],
       [0.38376579, 0.52396758],
       [0.63737754, 0.17962402]])

In [ ]:
import numpy as np

In [38]:
sample_array=np.arange(10,20)
sample_array

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
sample_array[9]

19

In [49]:
sample_array[2:5]

array([12, 13, 14])

In [50]:
sample_array[[2,5]]

array([12, 15])

In [40]:
sample_array[1:6]=100
sample_array

array([ 10, 100, 100, 100, 100, 100,  16,  17,  18,  19])

In [41]:
sample_array=np.arange(11,21)
sample_array[0:7]

array([11, 12, 13, 14, 15, 16, 17])

In [42]:
subset_sample_array=sample_array[1:7]
subset_sample_array

array([12, 13, 14, 15, 16, 17])

In [43]:
subset_sample_array[:]=100
subset_sample_array

array([100, 100, 100, 100, 100, 100])

### Two-Dimensional array

In [44]:
sample_matrix=np.array(([58,20,1,23],[25,23,21,33],[56,66,24,77]))
sample_matrix

array([[58, 20,  1, 23],
       [25, 23, 21, 33],
       [56, 66, 24, 77]])

In [45]:
sample_matrix[1][2]

21

In [46]:
sample_matrix[2,:]

array([56, 66, 24, 77])

In [47]:
sample_matrix[2]

array([56, 66, 24, 77])

### Custom indexing

In [48]:
sample_matrix=np.array(([30,10,11,23],[24,21,22,33],[6,76,24,37]))
sample_matrix

array([[30, 10, 11, 23],
       [24, 21, 22, 33],
       [ 6, 76, 24, 37]])

In [49]:
sample_matrix[:,(3,2)]

array([[23, 11],
       [33, 22],
       [37, 24]])

###  Selection techniques

In [50]:
sample_array=np.arange(11,31)
sample_array

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30])

In [51]:
bool=sample_array<11
bool

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [52]:
sample_array[bool]

array([], dtype=int32)

In [53]:
sample_array+sample_array

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60])

In [54]:
np.exp(sample_array)

array([5.98741417e+04, 1.62754791e+05, 4.42413392e+05, 1.20260428e+06,
       3.26901737e+06, 8.88611052e+06, 2.41549528e+07, 6.56599691e+07,
       1.78482301e+08, 4.85165195e+08, 1.31881573e+09, 3.58491285e+09,
       9.74480345e+09, 2.64891221e+10, 7.20048993e+10, 1.95729609e+11,
       5.32048241e+11, 1.44625706e+12, 3.93133430e+12, 1.06864746e+13])

In [55]:
np.sqrt(sample_array)

array([3.31662479, 3.46410162, 3.60555128, 3.74165739, 3.87298335,
       4.        , 4.12310563, 4.24264069, 4.35889894, 4.47213595,
       4.58257569, 4.69041576, 4.79583152, 4.89897949, 5.        ,
       5.09901951, 5.19615242, 5.29150262, 5.38516481, 5.47722558])

In [56]:
np.log(sample_array)

array([2.39789527, 2.48490665, 2.56494936, 2.63905733, 2.7080502 ,
       2.77258872, 2.83321334, 2.89037176, 2.94443898, 2.99573227,
       3.04452244, 3.09104245, 3.13549422, 3.17805383, 3.21887582,
       3.25809654, 3.29583687, 3.33220451, 3.36729583, 3.40119738])

In [57]:
np.max(sample_array)

30

In [58]:
np.min(sample_array)

11

In [59]:
np.argmax(sample_array)

19

In [60]:
np.argmin(sample_array)

0

In [61]:
np.square(sample_array)

array([121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529,
       576, 625, 676, 729, 784, 841, 900], dtype=int32)

In [64]:
np.std(sample_array)

5.766281297335398

In [63]:
np.var(sample_array)


33.25

In [65]:
np.mean(sample_array)

20.5

In [66]:
array=np.random.randn(3,6)
array

array([[-1.18775417,  2.01318163,  0.05415686, -1.20637899, -0.19944214,
         0.02148182],
       [ 1.50551219,  1.5834339 , -1.23785246,  0.08269609, -0.72974155,
        -0.5017089 ],
       [ 0.47272748,  0.09943591,  1.0303259 ,  1.67981739, -1.36229612,
        -0.80680881]])

In [67]:
np.round(array,decimals=2)

array([[-1.19,  2.01,  0.05, -1.21, -0.2 ,  0.02],
       [ 1.51,  1.58, -1.24,  0.08, -0.73, -0.5 ],
       [ 0.47,  0.1 ,  1.03,  1.68, -1.36, -0.81]])

In [68]:
sports=np.array(['golf','cricket','ftball','cricket'])
np.unique(sports)

array(['cricket', 'ftball', 'golf'], dtype='<U7')

In [69]:
import pandas as pd

In [72]:
df=pd.read_csv("https://raw.githubusercontent.com/justmarkham/DAT8/master/data/u.user")

In [81]:
labels=['a','b','c','d']
list=[10,22,34,40]
array=np.array([10,22,30,40])
dict={'w':10,'x':22,'y':30,'z':44}


In [76]:
pd.Series(data=list)

0    10
1    22
2    34
3    40
dtype: int64

In [75]:
pd.Series(data=list,index=labels)

a    10
b    22
c    34
d    40
dtype: int64

In [82]:
pd.Series(array,labels)

a    10
b    22
c    30
d    40
dtype: int32

In [83]:
pd.Series(dict)

w    10
x    22
y    30
z    44
dtype: int64

### Pandas dataframe and indexing

In [84]:
sports1=pd.Series([1,2,3,4],index=['archery','football','basketball','golf'])
sports1

archery       1
football      2
basketball    3
golf          4
dtype: int64

In [92]:
sports1['cricket']

1

In [85]:
sports2=pd.Series([11,2,3,4],index=['cricket','football','baseball','golf'])
sports2

cricket     11
football     2
baseball     3
golf         4
dtype: int64

In [86]:
sports1+sports2

archery       NaN
baseball      NaN
basketball    NaN
cricket       NaN
football      4.0
golf          8.0
dtype: float64

In [87]:
df1=pd.DataFrame(np.random.randn(8,5),index='A B C D E F G H '.split(),columns='Match1 Match2 Match3 Match4 Match5'.split())
df1


Match1    Match2    Match3    Match4    Match5
A -0.286883  0.046164 -1.416332  1.236724  1.735957
B -1.025902  0.979374 -1.357380 -0.592640 -0.309095
C  0.210397  0.212561 -0.214578  1.860849  0.629546
D -0.936968 -1.339352  0.925981  0.194844 -0.001815
E  0.102364  0.541947  1.347817 -0.065486 -1.090909
F  0.927350  0.026790 -0.185709 -1.537893  0.828748
G  0.951469  0.322768  1.189716 -1.593814 -0.730402
H -0.332611  0.424524  0.370651  0.933850  0.095194

In [89]:
df1['Match3']

A   -1.416332
B   -1.357380
C   -0.214578
D    0.925981
E    1.347817
F   -0.185709
G    1.189716
H    0.370651
Name: Match3, dtype: float64

In [90]:
df1[['Match2','Match1']]


Match2    Match1
A  0.046164 -0.286883
B  0.979374 -1.025902
C  0.212561  0.210397
D -1.339352 -0.936968
E  0.541947  0.102364
F  0.026790  0.927350
G  0.322768  0.951469
H  0.424524 -0.332611

In [91]:

df1['Score6']=df1['Match3']+df1['Match4']
df1



Match1    Match2    Match3    Match4    Match5    Score6
A -0.286883  0.046164 -1.416332  1.236724  1.735957 -0.179608
B -1.025902  0.979374 -1.357380 -0.592640 -0.309095 -1.950020
C  0.210397  0.212561 -0.214578  1.860849  0.629546  1.646270
D -0.936968 -1.339352  0.925981  0.194844 -0.001815  1.120825
E  0.102364  0.541947  1.347817 -0.065486 -1.090909  1.282331
F  0.927350  0.026790 -0.185709 -1.537893  0.828748 -1.723602
G  0.951469  0.322768  1.189716 -1.593814 -0.730402 -0.404097
H -0.332611  0.424524  0.370651  0.933850  0.095194  1.304501

In [92]:
df1.drop()



ValueError: Need to specify at least one of 'labels', 'index' or 'columns'

In [93]:
df1.reset_index()



index    Match1    Match2    Match3    Match4    Match5    Score6
0     A -0.286883  0.046164 -1.416332  1.236724  1.735957 -0.179608
1     B -1.025902  0.979374 -1.357380 -0.592640 -0.309095 -1.950020
2     C  0.210397  0.212561 -0.214578  1.860849  0.629546  1.646270
3     D -0.936968 -1.339352  0.925981  0.194844 -0.001815  1.120825
4     E  0.102364  0.541947  1.347817 -0.065486 -1.090909  1.282331
5     F  0.927350  0.026790 -0.185709 -1.537893  0.828748 -1.723602
6     G  0.951469  0.322768  1.189716 -1.593814 -0.730402 -0.404097
7     H -0.332611  0.424524  0.370651  0.933850  0.095194  1.304501

In [94]:
df2={'ID':['101','102','103','107','176'],'Name':['John','Mercy','Akash','Kavin','Lally'],'Profit':[22,55,97,13,23]}
df=pd.DataFrame(df2)
df

ID   Name  Profit
0  101   John      22
1  102  Mercy      55
2  103  Akash      97
3  107  Kavin      13
4  176  Lally      23